# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(blank=True, db_index=True, max_length=254),
                ),
                (
                    "primary_phone",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("traits", models.JSONField(default=dict)),
                ("is_anonymous", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_profile",
                        to="crm.customerprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_profiles",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_profiles",
            },
        ),
        migrations.CreateModel(
            name="MergeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_profile_id", models.UUIDField(db_index=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(default=dict)),
                ("merged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "merged_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the merge; null if automated",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_merges",
                        to="identity.identityprofile",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "identity_merge_events",
                "ordering": ["-merged_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentityAlias",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alias_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("device", "Device ID"),
                            ("cookie", "Cookie / Anonymous ID"),
                            ("user_id", "Internal User ID"),
                            ("external", "External ID"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("alias_value", models.CharField(db_index=True, max_length=512)),
                (
                    "source",
                    models.CharField(
                        blank=True, help_text="Origin system/channel", max_length=128
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(default=1.0, help_text="Match confidence 0–1"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="identity.identityprofile",
                    ),
                ),
            ],
            options={
                "db_table": "identity_aliases",
            },
        ),
        migrations.AddIndex(
            model_name="identityprofile",
            index=models.Index(
                fields=["tenant", "primary_email"],
                name="identity_pr_tenant__02c2c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="identityprofile",
            index=models.Index(
                fields=["tenant", "primary_phone"],
                name="identity_pr_tenant__e20c8d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="identityalias",
            unique_together={("profile", "alias_type", "alias_value")},
        ),
    ]
