# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("threshold", "Threshold Crossed"),
                            ("anomaly", "Anomaly Detected"),
                            ("manual", "Manual"),
                        ],
                        default="scheduled",
                        max_length=30,
                    ),
                ),
                ("metric_key", models.CharField(blank=True, max_length=128)),
                ("threshold_value", models.FloatField(blank=True, null=True)),
                ("query_config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_rules",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "insights_rules",
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend"),
                            ("anomaly", "Anomaly"),
                            ("recommendation", "Recommendation"),
                            ("forecast", "Forecast"),
                            ("cohort", "Cohort"),
                            ("funnel", "Funnel"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("summary", models.TextField()),
                ("data_points", models.JSONField(default=dict)),
                ("recommendation", models.TextField(blank=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="insights",
                        to="insights.insightrule",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "insights",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_read", "is_dismissed"],
                        name="insights_tenant__de4aa7_idx",
                    ),
                    models.Index(
                        fields=["insight_type", "priority"],
                        name="insights_insight_47ecc2_idx",
                    ),
                ],
            },
        ),
    ]
