# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "segment_type",
                    models.CharField(
                        choices=[("static", "Static"), ("dynamic", "Dynamic")],
                        default="dynamic",
                        max_length=20,
                    ),
                ),
                ("filter_conditions", models.JSONField(default=dict)),
                ("member_count", models.PositiveIntegerField(default=0)),
                ("auto_refresh", models.BooleanField(default=True)),
                ("last_refreshed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "segments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SegmentRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("field", models.CharField(max_length=200)),
                ("operator", models.CharField(max_length=50)),
                ("value", models.JSONField()),
                (
                    "logical_operator",
                    models.CharField(
                        choices=[("and", "AND"), ("or", "OR")],
                        default="and",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "db_table": "segment_rules",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SegmentMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("added_via", models.CharField(default="auto", max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="segments.segment",
                    ),
                ),
            ],
            options={
                "db_table": "segment_memberships",
                "unique_together": {("segment", "customer")},
            },
        ),
        migrations.AddField(
            model_name="segment",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="segments",
                through="segments.SegmentMembership",
                to="crm.customer",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="segments",
                to="tenants.tenant",
            ),
        ),
    ]
