# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=128)),
                (
                    "anonymous_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=2048)),
                ("utm_source", models.CharField(blank=True, max_length=255)),
                ("utm_medium", models.CharField(blank=True, max_length=255)),
                ("utm_campaign", models.CharField(blank=True, max_length=255)),
                ("utm_content", models.CharField(blank=True, max_length=255)),
                ("utm_term", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_identified", models.BooleanField(default=False)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions",
                        to="crm.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="RawEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("event_type", models.CharField(db_index=True, max_length=128)),
                ("event_name", models.CharField(max_length=255)),
                ("properties", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="raw_events",
                        to="crm.customer",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracking.session",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_events",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_raw_events",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                ("title", models.CharField(blank=True, max_length=512)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="tracking.session",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_page_views",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="IdentityMap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("anonymous_id", models.CharField(db_index=True, max_length=128)),
                ("resolved_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolution_method",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("email_capture", "Email Capture"),
                            ("api", "API"),
                            ("manual", "Manual"),
                        ],
                        default="login",
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_maps",
                        to="crm.customer",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_maps",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "tracking_identity_maps",
            },
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["tenant", "started_at"], name="tracking_se_tenant__d4daab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["anonymous_id"], name="tracking_se_anonymo_1155d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["tenant", "status"], name="tracking_ra_tenant__654757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawevent",
            index=models.Index(
                fields=["event_type", "received_at"],
                name="tracking_ra_event_t_66b51e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="identitymap",
            unique_together={("tenant", "anonymous_id")},
        ),
    ]
