# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_default", models.BooleanField(default=False)),
                ("layout", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_dashboards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "anonymous_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("event_name", models.CharField(db_index=True, max_length=255)),
                (
                    "category",
                    models.CharField(blank=True, db_index=True, max_length=100),
                ),
                ("properties", models.JSONField(default=dict)),
                ("context", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_events",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue Forecast"),
                            ("churn", "Churn Prediction"),
                            ("ltv", "Lifetime Value"),
                            ("demand", "Demand Forecast"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("last_trained_at", models.DateTimeField(blank=True, null=True)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("predictions", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "analytics_forecast_models",
            },
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("event_name", models.CharField(max_length=255)),
                (
                    "aggregation",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("sum", "Sum"),
                            ("avg", "Average"),
                            ("min", "Minimum"),
                            ("max", "Maximum"),
                            ("unique", "Unique Count"),
                        ],
                        default="count",
                        max_length=20,
                    ),
                ),
                ("field", models.CharField(blank=True, max_length=200)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("filters", models.JSONField(default=dict)),
                ("value", models.FloatField(default=0)),
                ("period_start", models.DateTimeField(blank=True, null=True)),
                ("period_end", models.DateTimeField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "analytics_metrics",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("query_config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_data", models.JSONField(default=dict)),
                (
                    "result_file",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                ("error_message", models.TextField(blank=True)),
                ("scheduled", models.BooleanField(default=False)),
                ("schedule_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "analytics_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("line", "Line Chart"),
                            ("bar", "Bar Chart"),
                            ("pie", "Pie Chart"),
                            ("metric", "Metric Card"),
                            ("table", "Table"),
                            ("funnel", "Funnel"),
                            ("cohort", "Cohort"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("position_x", models.IntegerField(default=0)),
                ("position_y", models.IntegerField(default=0)),
                ("width", models.IntegerField(default=4)),
                ("height", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="analytics.dashboard",
                    ),
                ),
            ],
            options={
                "db_table": "analytics_widgets",
                "ordering": ["position_y", "position_x"],
            },
        ),
    ]
