# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("event", "Event"),
                            ("segment_join", "Segment Join"),
                            ("manual", "Manual"),
                            ("schedule", "Schedule"),
                        ],
                        default="manual",
                        max_length=30,
                    ),
                ),
                ("trigger_config", models.JSONField(default=dict)),
                ("goal_config", models.JSONField(default=dict)),
                ("allow_re_entry", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "journeys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("wait", "Wait"),
                            ("send_email", "Send Email"),
                            ("send_sms", "Send SMS"),
                            ("condition", "Condition"),
                            ("update_field", "Update Field"),
                            ("webhook", "Webhook"),
                            ("end", "End"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("config", models.JSONField(default=dict)),
                ("order", models.PositiveIntegerField(default=0)),
                ("position_x", models.FloatField(default=0)),
                ("position_y", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="journeys.journey",
                    ),
                ),
                (
                    "next_step_on_failure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="failure_previous_steps",
                        to="journeys.journeystep",
                    ),
                ),
                (
                    "next_step_on_success",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="previous_steps",
                        to="journeys.journeystep",
                    ),
                ),
            ],
            options={
                "db_table": "journey_steps",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JourneyEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "current_step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="journeys.journeystep",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_enrollments",
                        to="crm.customer",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="journeys.journey",
                    ),
                ),
            ],
            options={
                "db_table": "journey_enrollments",
                "ordering": ["-enrolled_at"],
                "indexes": [
                    models.Index(
                        fields=["journey", "status"],
                        name="journey_enr_journey_bb0c58_idx",
                    )
                ],
            },
        ),
    ]
