# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carrier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50)),
                (
                    "tracking_url_template",
                    models.URLField(
                        blank=True,
                        help_text="Use {tracking_number} as placeholder, e.g. https://track.ups.com/?tracknum={tracking_number}",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="API credentials and options"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carriers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_carriers",
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="FulfillmentCenter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("address", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fulfillment_centers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_fulfillment_centers",
            },
        ),
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "countries",
                    models.JSONField(
                        default=list, help_text="ISO 3166-1 alpha-2 country codes"
                    ),
                ),
                (
                    "states",
                    models.JSONField(default=list, help_text="State/province codes"),
                ),
                ("zip_codes", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipping_zones",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_shipping_zones",
            },
        ),
        migrations.CreateModel(
            name="ShippingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rate_type",
                    models.CharField(
                        choices=[
                            ("flat", "Flat Rate"),
                            ("weight", "Weight-Based"),
                            ("order_value", "Order Value Based"),
                            ("per_item", "Per Item"),
                            ("free", "Free Shipping"),
                        ],
                        default="flat",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_order_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                (
                    "max_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=8, null=True
                    ),
                ),
                ("estimated_days_min", models.PositiveSmallIntegerField(default=1)),
                ("estimated_days_max", models.PositiveSmallIntegerField(default=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.carrier",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="logistics.shippingzone",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_shipping_rates",
            },
        ),
        migrations.CreateModel(
            name="ShipmentTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shipment_id", models.UUIDField(db_index=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pre_transit", "Pre-Transit"),
                            ("in_transit", "In Transit"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed Delivery"),
                            ("returned", "Returned"),
                        ],
                        db_index=True,
                        default="pre_transit",
                        max_length=30,
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of {timestamp, location, description}",
                    ),
                ),
                ("estimated_delivery", models.DateField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.carrier",
                    ),
                ),
                (
                    "fulfillment_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.fulfillmentcenter",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment_trackings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "logistics_shipment_trackings",
                "ordering": ["-created_at"],
            },
        ),
    ]
