# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("first_name", models.CharField(blank=True, max_length=150)),
                ("last_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("company", models.CharField(blank=True, max_length=255)),
                ("job_title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Lead"),
                            ("prospect", "Prospect"),
                            ("active", "Active"),
                            ("churned", "Churned"),
                            ("inactive", "Inactive"),
                        ],
                        db_index=True,
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(default=list)),
                ("custom_fields", models.JSONField(default=dict)),
                ("opted_in_email", models.BooleanField(default=True)),
                ("opted_in_sms", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "crm_customers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engagement_score", models.FloatField(default=0.0)),
                ("lead_score", models.FloatField(default=0.0)),
                ("churn_risk_score", models.FloatField(default=0.0)),
                (
                    "lifetime_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "predicted_ltv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("recency_days", models.IntegerField(default=0)),
                ("frequency_count", models.IntegerField(default=0)),
                (
                    "monetary_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_scores",
            },
        ),
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("communication_channels", models.JSONField(default=list)),
                ("frequency", models.CharField(default="weekly", max_length=20)),
                ("interests", models.JSONField(default=list)),
                ("product_categories", models.JSONField(default=list)),
                ("do_not_contact", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_preferences",
            },
        ),
        migrations.CreateModel(
            name="LifecycleStage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("awareness", "Awareness"),
                            ("consideration", "Consideration"),
                            ("purchase", "Purchase"),
                            ("retention", "Retention"),
                            ("advocacy", "Advocacy"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("trigger", models.CharField(blank=True, max_length=200)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lifecycle_stages",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_lifecycle_stages",
                "ordering": ["-entered_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("address", models.JSONField(default=dict)),
                ("social_profiles", models.JSONField(default=dict)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("language", models.CharField(default="en", max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "crm_customer_profiles",
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interaction_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("call", "Call"),
                            ("meeting", "Meeting"),
                            ("chat", "Chat"),
                            ("sms", "SMS"),
                            ("note", "Note"),
                            ("purchase", "Purchase"),
                            ("support", "Support"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField(blank=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        default="outbound",
                        max_length=10,
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.customer",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crm_interactions",
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-occurred_at"],
                        name="crm_interac_custome_2eee04_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "status"], name="crm_custome_tenant__4f38c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["tenant", "email"], name="crm_custome_tenant__5608b1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("tenant", "email")},
        ),
    ]
