# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crm", "0001_initial"),
        ("segments", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ab_test_enabled", models.BooleanField(default=False)),
                ("ab_test_config", models.JSONField(default=dict)),
                ("utm_params", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "comm_campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-App"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("bounced", "Bounced"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=500)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="communications.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_logs",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "db_table": "comm_delivery_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-App"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("html_body", models.TextField(blank=True)),
                ("variables", models.JSONField(default=list)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_templates",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "comm_message_templates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EngagementMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("click", "Click"),
                            ("reply", "Reply"),
                            ("unsubscribe", "Unsubscribe"),
                            ("bounce", "Bounce"),
                            ("spam", "Spam Report"),
                            ("conversion", "Conversion"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("url_clicked", models.URLField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(default=dict)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_metrics",
                        to="communications.deliverylog",
                    ),
                ),
            ],
            options={
                "db_table": "comm_engagement_metrics",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("whatsapp", "WhatsApp"),
                            ("in_app", "In-App"),
                            ("webhook", "Webhook"),
                        ],
                        max_length=30,
                    ),
                ),
                ("config", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "comm_channels",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="channel",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="communications.channel",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="segments.segment",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="communications.messagetemplate",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="tenants.tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(
                fields=["campaign", "status"], name="comm_delive_campaig_872d13_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverylog",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="comm_delive_custome_35941f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="channel",
            unique_together={("tenant", "channel_type", "name")},
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["tenant", "status"], name="comm_campai_tenant__eacd48_idx"
            ),
        ),
    ]
