# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=512)),
                ("description", models.TextField(blank=True)),
                ("logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("maintenance", "Maintenance"),
                            ("inactive", "Inactive"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("address", models.JSONField(default=dict)),
                ("social_links", models.JSONField(default=dict)),
                ("analytics_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stores",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "storefront_stores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StoreTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("primary_color", models.CharField(default="#3b82f6", max_length=7)),
                ("secondary_color", models.CharField(default="#6366f1", max_length=7)),
                ("accent_color", models.CharField(default="#f59e0b", max_length=7)),
                ("background_color", models.CharField(default="#ffffff", max_length=7)),
                ("font_heading", models.CharField(default="Inter", max_length=100)),
                ("font_body", models.CharField(default="Inter", max_length=100)),
                ("custom_css", models.TextField(blank=True)),
                ("header_layout", models.CharField(default="standard", max_length=30)),
                ("footer_layout", models.CharField(default="standard", max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="storefront.store",
                    ),
                ),
            ],
            options={
                "db_table": "storefront_themes",
            },
        ),
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tax_enabled", models.BooleanField(default=True)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                ("tax_inclusive", models.BooleanField(default=False)),
                ("guest_checkout", models.BooleanField(default=True)),
                ("inventory_tracking", models.BooleanField(default=True)),
                ("allow_backorders", models.BooleanField(default=False)),
                (
                    "min_order_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "max_order_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("payment_methods", models.JSONField(default=list)),
                ("shipping_methods", models.JSONField(default=list)),
                ("notification_emails", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="storefront.store",
                    ),
                ),
            ],
            options={
                "db_table": "storefront_settings",
            },
        ),
        migrations.CreateModel(
            name="StorePage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("about", "About"),
                            ("contact", "Contact"),
                            ("policy", "Policy"),
                            ("landing", "Landing Page"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("slug", models.SlugField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("blocks", models.JSONField(default=list)),
                ("meta_title", models.CharField(blank=True, max_length=512)),
                ("meta_description", models.CharField(blank=True, max_length=1024)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="storefront.store",
                    ),
                ),
            ],
            options={
                "db_table": "storefront_pages",
                "ordering": ["title"],
                "unique_together": {("store", "slug")},
            },
        ),
    ]
