# Generated by Django 4.2.13 on 2026-04-18 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commerce", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("meta_title", models.CharField(blank=True, max_length=512)),
                ("meta_description", models.CharField(blank=True, max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "merchandising_collections",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage Adjustment"),
                            ("fixed_amount", "Fixed Amount Off"),
                            ("fixed_price", "Set Fixed Price"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All Products"),
                            ("product", "Specific Product"),
                            ("category", "Category"),
                            ("collection", "Collection"),
                            ("customer_segment", "Customer Segment"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "scope_ids",
                    models.JSONField(
                        default=list,
                        help_text="IDs of products/categories/etc. this applies to",
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("min_quantity", models.PositiveIntegerField(default=1)),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher = applied first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_rules",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "merchandising_pricing_rules",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="FeaturedProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "slot_name",
                    models.CharField(
                        help_text="e.g. homepage_hero, category_top", max_length=100
                    ),
                ),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, help_text="e.g. 'New', 'Hot', 'Sale'", max_length=50
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_slots",
                        to="commerce.product",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_products",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "merchandising_featured_products",
                "ordering": ["slot_name", "position"],
            },
        ),
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="merchandising.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commerce.product",
                    ),
                ),
            ],
            options={
                "db_table": "merchandising_collection_products",
                "ordering": ["position"],
                "unique_together": {("collection", "product")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="merchandising.CollectionProduct",
                to="commerce.product",
            ),
        ),
        migrations.AddField(
            model_name="collection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collections",
                to="tenants.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=512)),
                ("image_url", models.URLField(blank=True)),
                ("mobile_image_url", models.URLField(blank=True)),
                ("link_url", models.URLField(blank=True)),
                ("cta_text", models.CharField(blank=True, max_length=100)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Banner"),
                            ("header", "Header Bar"),
                            ("sidebar", "Sidebar"),
                            ("product_page", "Product Page"),
                            ("category_page", "Category Page"),
                            ("checkout", "Checkout Page"),
                            ("popup", "Popup"),
                        ],
                        default="hero",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "merchandising_banners",
                "ordering": ["placement", "sort_order"],
            },
        ),
    ]
